<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <OutputType>Library</OutputType>
    <PackageId>Lmc.Neo4j</PackageId>
    <Version>3.1.0</Version>
    <RepositoryUrl>https://bitbucket.lmc.cz/projects/ARCHI/repos/fneo4j/browse</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="AssemblyInfo.fs" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="src/Utils.fs" />

    <Compile Include="src/Client.fs" />
    <Compile Include="src/Types.fs" />

    <Compile Include="src/CypherTypes.fs" />
    <Compile Include="src/CypherFluentQuery.fs" />
    <Compile Include="src/RawCypherQuery.fs" />
    <Compile Include="src/CypherQuery.fs" />

    <Compile Include="src/Dto.fs" />
  </ItemGroup>

  <Import Project=".paket\Paket.Restore.targets" />
</Project>
